version: '3'

services:
  db:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: "cnab-backend"
      POSTGRES_USER: "cnab-backend"
      POSTGRES_PASSWORD: "cnab-backend"
    ports:
      - "5432:5432"
    #volumes:
##      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql